### ISSUE TITLE
Sample Example

### ISSUE THREAD

**Issue by Noor-Kalibbala** [regosen/get_cover_art#1]
please can u add a simple example of getting artwork for a file

**Comment by regosen** [comment]
Thanks for the suggestion @Noor-Kalibbala , I've just added support for using a single file instead of a folder.  I also updated the README accordingly:

Here's a single-file example from the commandline:
```
python -m get_cover_art --path=<PATH_TO_AUDIO_FILE>
```

And here's an example from the Python environment:
```
from get_cover_art import CoverFinder
finder = CoverFinder()
finder.scan_file(PATH_TO_AUDIO_FILE)
```

Where `PATH_TO_AUDIO_FILE` can be an absolute path or a relative path.

If you update to the latest version of get_cover_art, you should be able to run with the above examples.

**Comment by Noor-Kalibbala** [comment]
@regosen thank u for your feedback 🙏
