### ISSUE TITLE
Delete _cover_art folder when done

### ISSUE THREAD

**Issue by julianfairfax** [regosen/get_cover_art#30]
It would be nice if this tool deleted the folder it creates when the command specified is done running

**Comment by regosen** [comment]
This is a good idea, though I would want it to be opt-in.  I'm thinking of what to call the option, do you have any suggestions?

**Comment by julianfairfax** [comment]
--no-cache? or maybe --clear-cache to clear it?

**Comment by regosen** [comment]
I kinda like that, though when I see a "cache" option I usually expect it to clear cache before running the tool, not after.  So I went with --cleanup instead, because that infers a post-cleanup to me.

I just posted a new version with this option (1.6.2), please let me know if it doesn't work as expected!

**Comment by julianfairfax** [comment]
It does, but if it skips the files it still creates the folder and doesn't clean it up afterwards. This should be changed to clean up in all cases.

**Comment by regosen** [comment]
Ah, good point.  Ok, I just posted a new version (1.6.3).

**Comment by julianfairfax** [comment]
Works
